apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: openrouter-backend-tls
  namespace: default
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: openrouter-api-backend-eg
  validation:
    hostname: openrouter.ai
    wellKnownCACertificates: System
