apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: openrouter-api-key-policy-external
  namespace: default
spec:
  type: APIKey
  apiKey:
    secretRef:
      name: openrouter-secret
      kind: Secret
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: ai-service-openrouter-external
